FROM node:18-slim
WORKDIR /app
COPY package*.json ./
ENV NODE_ENV=development
ENV NPM_CONFIG_PRODUCTION=false
RUN npm install --no-audit --no-fund
RUN test -f node_modules/.bin/react-scripts || (echo "!!! react-scripts NOT installed" && exit 1)
EXPOSE 3000
CMD ["npm", "start"]
